# -*- coding: utf-8 -*-
"""Image Classifier Project - Modified - v1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/127Gj7XlTcZxWMhCFLve08slk6lkIEcgq

# Developing an AI application

## **NOTE:** 

This is slightly edited notebook to help you with downloaing and loading image datasets. I have left the exercise parts untouched and you have to fill them, ofcourse. If you have any issue with this notebook, feel free to contact me `avinash` on Slack :D

Going forward, AI algorithms will be incorporated into more and more everyday applications. For example, you might want to include an image classifier in a smart phone app. To do this, you'd use a deep learning model trained on hundreds of thousands of images as part of the overall application architecture. A large part of software development in the future will be using these types of models as common parts of applications. 

In this project, you'll train an image classifier to recognize different species of flowers. You can imagine using something like this in a phone app that tells you the name of the flower your camera is looking at. In practice you'd train this classifier, then export it for use in your application. We'll be using [this dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html) of 102 flower categories, you can see a few examples below. 

<img src='https://github.com/udacity/pytorch_challenge/blob/master/assets/Flowers.png?raw=1' width=500px>

The project is broken down into multiple steps:

* Load and preprocess the image dataset
* Train the image classifier on your dataset
* Use the trained classifier to predict image content

We'll lead you through each part which you'll implement in Python.

When you've completed this project, you'll have an application that can be trained on any set of labeled images. Here your network will be learning about flowers and end up as a command line application. But, what you do with your new skills depends on your imagination and effort in building a dataset. For example, imagine an app where you take a picture of a car, it tells you what the make and model is, then looks up information about it. Go build your own dataset and make something new.

First up is importing the packages you'll need. It's good practice to keep all the imports at the beginning of your code. As you work through this notebook and find you need to import a package, make sure to add the import up here.

# Mount Google Driver to Save the Models
"""

# Install a Drive FUSE wrapper.
# https://github.com/astrada/google-drive-ocamlfuse
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse

# Generate auth tokens for Colab
from google.colab import auth
auth.authenticate_user()

# Generate creds for the Drive FUSE library.
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

# Create a directory and mount Google Drive using that directory.
!mkdir -p drive
!google-drive-ocamlfuse drive

"""# Tips, Model Performance, Submission Troubleshooting, etc 

The amazing people at Slack have compiled an amazing list of tips for this project. Check it here - [link](https://docs.google.com/document/d/1-MCDPOejsn2hq9EoBzMpzGv9jEdtMWoIwjkAa1cVbSM/edit#heading=h.yspy8tt3f0xe)
"""

# google colab does not come with torch installed. And also, in course we are using torch 0.4. 
# so following snippet of code installs the relevant version

from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

# we will verify that GPU is enabled for this notebook
# following should print: CUDA is available!  Training on GPU ...
# 
# if it prints otherwise, then you need to enable GPU: 
# from Menu > Runtime > Change Runtime Type > Hardware Accelerator > GPU

import torch
import numpy as np

# check if CUDA is available
train_on_gpu = torch.cuda.is_available()

if not train_on_gpu:
    print('CUDA is not available.  Training on CPU ...')
else:
    print('CUDA is available!  Training on GPU ...')

# we need pillow version of 5.3.0
# we will uninstall the older version first
!pip uninstall -y Pillow
# install the new one
!pip install Pillow==5.3.0
# import the new one
import PIL
print(PIL.PILLOW_VERSION)
# this should print 5.3.0. If it doesn't, then restart your runtime:
# Menu > Runtime > Restart Runtime

# Imports here
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

import torch
from torch import nn
from torch.nn import functional as F

from torchvision import models
from torchvision import transforms
from torchvision import datasets

# %matplotlib inline

# Constants
BATCH_SIZE = 64
NUM_WORKERS = 2

TRAIN_ON_GPU = torch.cuda.is_available()
print("Training on ", "GPU" if TRAIN_ON_GPU else "CPU")

"""## Load the data

Here you'll use `torchvision` to load the data ([documentation](http://pytorch.org/docs/0.3.0/torchvision/index.html)). You can [download the data here](https://s3.amazonaws.com/content.udacity-data.com/courses/nd188/flower_data.zip). The dataset is split into two parts, training and validation. For the training, you'll want to apply transformations such as random scaling, cropping, and flipping. This will help the network generalize leading to better performance. If you use a pre-trained network, you'll also need to make sure the input data is resized to 224x224 pixels as required by the networks.

The validation set is used to measure the model's performance on data it hasn't seen yet. For this you don't want any scaling or rotation transformations, but you'll need to resize then crop the images to the appropriate size.

The pre-trained networks available from `torchvision` were trained on the ImageNet dataset where each color channel was normalized separately. For both sets you'll need to normalize the means and standard deviations of the images to what the network expects. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`, calculated from the ImageNet images.  These values will shift each color channel to be centered at 0 and range from -1 to 1.
"""

# we will download the required data files
!wget -cq https://github.com/udacity/pytorch_challenge/raw/master/cat_to_name.json
!wget -cq https://s3.amazonaws.com/content.udacity-data.com/courses/nd188/flower_data.zip
!rm -r flower_data || true
!unzip -qq flower_data.zip

data_dir = 'flower_data'
train_dir = data_dir + '/train'
valid_dir = data_dir + '/valid'

# TODO: Define your transforms for the training and validation sets
train_transforms = transforms.Compose([
    transforms.Resize(255),
    transforms.RandomHorizontalFlip(),
    transforms.RandomRotation(30),
    transforms.RandomCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        (0.485, 0.456, 0.406),
        (0.229, 0.224, 0.225)
    )
])

valid_transforms = transforms.Compose([
    transforms.Resize(255),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
        (0.485, 0.456, 0.406),
        (0.229, 0.224, 0.225)
    )
])

# TODO: Load the datasets with ImageFolder
train_dataset = datasets.ImageFolder(train_dir, transform=train_transforms)

valid_dataset = datasets.ImageFolder(valid_dir, transform=valid_transforms)

# import pdb; pdb.set_trace()
valid_dataset_len = len(valid_dataset)//2
valid_dataset, test_dataset = torch.utils.data.random_split(
    valid_dataset, 
    (valid_dataset_len, valid_dataset_len)
)

# TODO: Using the image datasets and the trainforms, define the dataloaders
train_dataloader = torch.utils.data.DataLoader(
    train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=NUM_WORKERS)

valid_dataloader = torch.utils.data.DataLoader(
    valid_dataset, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

test_dataloader = torch.utils.data.DataLoader(
    test_dataset, batch_size=BATCH_SIZE, num_workers=NUM_WORKERS)

print(
    len(train_dataset),
    len(valid_dataset),
    len(test_dataset)
)

"""### Label mapping

You'll also need to load in a mapping from category label to category name. You can find this in the file `cat_to_name.json`. It's a JSON object which you can read in with the [`json` module](https://docs.python.org/2/library/json.html). This will give you a dictionary mapping the integer encoded categories to the actual names of the flowers.
"""

import json

with open('cat_to_name.json', 'r') as f:
    cat_to_name = json.load(f)

"""## Image Preprocessing

You'll want to use `PIL` to load the image ([documentation](https://pillow.readthedocs.io/en/latest/reference/Image.html)). It's best to write a function that preprocesses the image so it can be used as input for the model. This function should process the images in the same manner used for training. 

First, resize the images where the shortest side is 256 pixels, keeping the aspect ratio. This can be done with the [`thumbnail`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) or [`resize`](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.thumbnail) methods. Then you'll need to crop out the center 224x224 portion of the image.

Color channels of images are typically encoded as integers 0-255, but the model expected floats 0-1. You'll need to convert the values. It's easiest with a Numpy array, which you can get from a PIL image like so `np_image = np.array(pil_image)`.

As before, the network expects the images to be normalized in a specific way. For the means, it's `[0.485, 0.456, 0.406]` and for the standard deviations `[0.229, 0.224, 0.225]`. You'll want to subtract the means from each color channel, then divide by the standard deviation. 

And finally, PyTorch expects the color channel to be the first dimension but it's the third dimension in the PIL image and Numpy array. You can reorder dimensions using [`ndarray.transpose`](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.transpose.html). The color channel needs to be first and retain the order of the other two dimensions.
"""

def load_image(image_path):
    image = Image.open(image_path).convert('RGB')
    return image

def process_image(image):
    ''' Scales, crops, and normalizes a PIL image for a PyTorch model,
        returns an Numpy array
    '''
    
    # TODO: Process a PIL image for use in a PyTorch model
    image = valid_transforms(image)
    image = image[:3,:,:].unsqueeze(0)
    return image

"""To check your work, the function below converts a PyTorch tensor and displays it in the notebook. If your `process_image` function works, running the output through this function should return the original image (except for the cropped out portions)."""

def imshow(image, ax=None, title=None):
    """Imshow for Tensor."""
    if ax is None:
        fig, ax = plt.subplots()
    
    # PyTorch tensors assume the color channel is the first dimension
    # but matplotlib assumes is the third dimension

    image = image[0].numpy().transpose((1, 2, 0))
    
    # Undo preprocessing
    mean = np.array([0.485, 0.456, 0.406])
    std = np.array([0.229, 0.224, 0.225])
    image = std * image + mean
    
    # Image needs to be clipped between 0 and 1 or it looks like noise when displayed
    image = np.clip(image, 0, 1)
    
    ax.imshow(image)
    
    return ax

image = load_image(image_path='flower_data/valid/90/image_04402.jpg')
image = process_image(image)

imshow(image, title=cat_to_name['90'])
print(cat_to_name['90'])
print(image.shape)

# Visualise some sample data
def plot_img_samples(images, labels, sample_size=20):
#     images = images.numpy()    
    fig = plt.figure(figsize=(25, 4))
    
#     mean = np.array([0.485, 0.456, 0,406])
#     std = np.array([0.229, 0.224, 0,225])
    
    
    for idx in np.arange(sample_size):
#         image = np.transpose(images[idx], (1, 2, 0))
#         image = std * image + mean
#         image = np.clip(image, 0, 1)
        
        ax = fig.add_subplot(2, sample_size/2, idx+1, xticks=[], yticks=[])
#         plt.imshow(image)
        ax.set_title(cat_to_name[str(labels[idx].item())])
        
        imshow(images[idx], ax, title=cat_to_name[str(labels[idx].item())])
        
images, labels = next(iter(train_dataloader))
# plot_img_samples(images, labels)

"""# Building and training the classifier

Now that the data is ready, it's time to build and train the classifier. As usual, you should use one of the pretrained models from `torchvision.models` to get the image features. Build and train a new feed-forward classifier using those features.

We're going to leave this part up to you. If you want to talk through it with someone, chat with your fellow students! You can also ask questions on the forums or join the instructors in office hours.

Refer to [the rubric](https://review.udacity.com/#!/rubrics/1663/view) for guidance on successfully completing this section. Things you'll need to do:

* Load a [pre-trained network](http://pytorch.org/docs/master/torchvision/models.html) (If you need a starting point, the VGG networks work great and are straightforward to use)
* Define a new, untrained feed-forward network as a classifier, using ReLU activations and dropout
* Train the classifier layers using backpropagation using the pre-trained network to get the features
* Track the loss and accuracy on the validation set to determine the best hyperparameters

We've left a cell open for you below, but use as many as you need. Our advice is to break the problem up into smaller parts you can run separately. Check that each part is doing what you expect, then move on to the next. You'll likely find that as you work through each part, you'll need to go back and modify your previous code. This is totally normal!

When training make sure you're updating only the weights of the feed-forward network. You should be able to get the validation accuracy above 70% if you build everything right. Make sure to try different hyperparameters (learning rate, units in the classifier, epochs, etc) to find the best model. Save those hyperparameters to use as default values in the next part of the project.
"""

# Download pre-pretrained network and change de classifier
model = models.vgg16(pretrained=True)

# Freeze params
for param in model.features.parameters():
    param.requires_grad = False

model.classifier = nn.Sequential(
    nn.Linear(in_features=25088, out_features=4096, bias=True),
    nn.ReLU(inplace=True),
    nn.Dropout(p=0.5),
    nn.Linear(in_features=4096, out_features=4096, bias=True),
    nn.ReLU(inplace=True),
    nn.Dropout(p=0.5),
    nn.Linear(in_features=4096, out_features=102, bias=True)
)

if TRAIN_ON_GPU:
    model.cuda()
    model.features.cuda()
    model.classifier.cuda()
    
model.class_to_idx = cat_to_name
    
print(model)

# Define Hyper params
epochs = 50

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.classifier.parameters(), lr=0.01, momentum=0.4)

# %config InilineBackend.figura_format = 'retina'
def plot_loss(train_losses, valid_losses):
    plt.plot(train_losses, label='Train Loss')
    plt.plot(valid_losses, label='Validation Loss')
    plt.legend(frameon=False)

"""## Save the checkpoint

Now that your network is trained, save the model so you can load it later for making predictions. You probably want to save other things such as the mapping of classes to indices which you get from one of the image datasets: `image_datasets['train'].class_to_idx`. You can attach this to the model as an attribute which makes inference easier later on.

```model.class_to_idx = image_datasets['train'].class_to_idx```

Remember that you'll want to completely rebuild the model later so you can use it for inference. Make sure to include any information you need in the checkpoint. If you want to load the model and keep training, you'll want to save the number of epochs as well as the optimizer state, `optimizer.state_dict`. You'll likely want to use this trained model in the next part of the project, so best to save it now.
"""

# TODO: Save the checkpoint 
def save_classifier_checkpoint(model, optimizer, trained_epochs):
    print('Saving model...')
    
    checkpoint = {
        'input_size': 25088,
        'output_size': 102,
#         'hidden_layers': [each.out_features for each in model.hidden_layers],
        'model_type': str(type(model)),
        'state_dict': model.classifier.state_dict(),
        'optimizer': {
            'type': str(type(optimizer)),
            'state_dict': optimizer.state_dict(),
            'lr': optimizer.defaults['lr'],
            'momentum': optimizer.defaults['momentum']
        },
        'class_to_idx': model.class_to_idx
    }
    checkpoint_path = 'drive/Colab Notebooks/image_classifier_checkpoints'
    
    #torch.save(
    #    checkpoint, 
    #    f'{checkpoint_path}/classifier_state_dict_e{trained_epochs}.pth')
    
    torch.save(
        checkpoint, f'{checkpoint_path}/classifier_state_dict.pth')

def train_network(model, epochs, criterion, optimizer, train_dataloader, valid_dataloader):
    min_valid_loss = float('inf')
    train_losses = np.zeros(epochs)
    valid_losses = np.zeros(epochs)
        
#     if TRAIN_ON_GPU:
#         train_losses = train_losses.cuda()
#         valid_losses = valid_losses.cuda()

    for epoch in range(epochs):
#         print(f'Starting epoch {epoch}')
        
        accuracy = 0
        model.train()
        for images, labels in train_dataloader:
            if TRAIN_ON_GPU:
                images, labels = images.cuda(), labels.cuda()
            
            optimizer.zero_grad()
            
            #TODO: Reshape input
            output = model(images)
            
            loss = criterion(output, labels)
            loss.backward()
            
            optimizer.step()
            
            train_losses[epoch] += loss.item()
            
        else:
            train_losses[epoch] = train_losses[epoch] / len(train_dataloader)
        
        with torch.no_grad():
            model.eval()
            for images, labels in valid_dataloader:
                if TRAIN_ON_GPU:
                    images, labels = images.cuda(), labels.cuda()

                output = model(images)

                _, prediction = F.softmax(output, dim=1).topk(1)
                equality = labels.view(*prediction.shape) == prediction
#                 accuracy += torch.mean(equality.type(torch.FloatTensor))

                accuracy += torch.mean(equality.double())
                

                valid_losses[epoch] += criterion(output, labels).item()
            else:
                valid_losses[epoch] = valid_losses[epoch] / len(valid_dataloader)
                accuracy = accuracy / len(valid_dataloader)

                if valid_losses[epoch] <= min_valid_loss:
                    save_classifier_checkpoint(
                        model, optimizer, trained_epochs=epoch)
                    
                    min_valid_loss = valid_losses[epoch]
        
        print(
            f'epoch: {epoch}\t',
            f'train_loss: {train_losses[epoch]:3f}\t',
            f'valid_loss: {valid_losses[epoch]:3f}\t',
            f'accuracy: {accuracy:3f}'
        )
    
    plot_loss(train_losses, valid_losses)

# TODO: Build and train your network
# train_network(model, epochs, criterion, optimizer, train_dataloader, valid_dataloader)

"""## Loading the checkpoint

At this point it's good to write a function that can load a checkpoint and rebuild the model. That way you can come back to this project and keep working on it without having to retrain the network.
"""

# TODO: Write a function that loads a checkpoint and rebuilds the model
def mount_model(checkpoint):
    model = models.vgg16(pretrained=True)
    for param in model.features.parameters():
        param.requires_grad = False
    
    model.classifier = nn.Sequential(
        nn.Linear(in_features=25088, out_features=4096, bias=True),
        nn.ReLU(inplace=True),
        nn.Dropout(p=0.5),
        nn.Linear(in_features=4096, out_features=4096, bias=True),
        nn.ReLU(inplace=True),
        nn.Dropout(p=0.5),
        nn.Linear(in_features=4096, out_features=102, bias=True)
    )
    
    model.classifier.load_state_dict(checkpoint['state_dict'])
    
    model.class_to_idx = checkpoint['class_to_idx']
    
    return model

def load_checkpoint(filepath=None):
    if filepath is None:
        filepath = 'drive/Colab Notebooks/image_classifier_checkpoints/classifier_state_dict.pth'
        
    checkpoint = torch.load(filepath)
    # Todo: finish
    model = mount_model(checkpoint)
    
    optimizer = torch.optim.SGD(
        model.classifier.parameters(),
        lr=checkpoint['optimizer']['lr'],
        momentum=checkpoint['optimizer']['momentum']
    )
    optimizer.load_state_dict(checkpoint['optimizer']['state_dict'])
    return model, optimizer

best_model, trained_optimizer = load_checkpoint()
# print(best_model)
# print(trained_optimizer)

"""# Inference for classification

Now you'll write a function to use a trained network for inference. That is, you'll pass an image into the network and predict the class of the flower in the image. Write a function called `predict` that takes an image and a model, then returns the top $K$ most likely classes along with the probabilities. It should look like 

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

First you'll need to handle processing the input image such that it can be used in your network.

## Class Prediction

Once you can get images in the correct format, it's time to write a function for making predictions with your model. A common practice is to predict the top 5 or so (usually called top-$K$) most probable classes. You'll want to calculate the class probabilities then find the $K$ largest values.

To get the top $K$ largest values in a tensor use [`x.topk(k)`](http://pytorch.org/docs/master/torch.html#torch.topk). This method returns both the highest `k` probabilities and the indices of those probabilities corresponding to the classes. You need to convert from these indices to the actual class labels using `class_to_idx` which hopefully you added to the model or from an `ImageFolder` you used to load the data ([see here](#Save-the-checkpoint)). Make sure to invert the dictionary so you get a mapping from index to class as well.

Again, this method should take a path to an image and a model checkpoint, then return the probabilities and classes.

```python
probs, classes = predict(image_path, model)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```
"""

def predict(image_path, model, topk=5):
    ''' Predict the class (or classes) of an image using a trained deep learning model.
    '''
    
    # TODO: Implement the code to predict the class from an image file
    with torch.no_grad():
        image = load_image(image_path)
        image = process_image(image)

        model.eval()
        output = model(image)
        probabilities, predict_classes = F.softmax(output, dim=1).topk(topk, dim=1)
        
        predict_classes = [str(c.item()) for c in predict_classes.squeeze(0)]

    return probabilities.squeeze(), predict_classes

"""## Sanity Checking

Now that you can use a trained model for predictions, check to make sure it makes sense. Even if the validation accuracy is high, it's always good to check that there aren't obvious bugs. Use `matplotlib` to plot the probabilities for the top 5 classes as a bar graph, along with the input image. It should look like this:

<img src='https://github.com/udacity/pytorch_challenge/blob/master/assets/inference_example.png?raw=1' width=300px>

You can convert from the class integer encoding to actual flower names with the `cat_to_name.json` file (should have been loaded earlier in the notebook). To show a PyTorch tensor as an image, use the `imshow` function defined above.
"""

def view_classify(img, ps, labels, label_map, version="IRIS"):
    ''' Function for viewing an image and it's predicted classes.
    '''
    ps = ps.data.numpy().squeeze()

#     fig, (ax1, ax2) = plt.subplots(figsize=(6,9), ncols=2)
    fig, ax2 = plt.subplots(figsize=(6,9), ncols=1)
    
#     ax1.imshow(img.resize_(1, 28, 28).numpy().squeeze())
#     ax1.axis('off')
    ax2.barh(np.arange(len(ps)), ps)
    ax2.set_aspect(0.1)
    ax2.set_yticks(np.arange(len(ps)))

    ax2.set_yticklabels(
        [label_map[l] for l in labels], 
        size='small'
    )
    
    ax2.set_title('Class Probability')
    ax2.set_xlim(0, 1.1)

    plt.tight_layout()

# TODO: Display an image along with the top 5 classes
# %matplotlib inline
# %config InlineBackend.figure_format = 'retina'

image_path = 'flower_data/valid/90/image_04402.jpg'
image = load_image(image_path)
image = process_image(image)


probs, classes = predict(
    image_path=image_path,
    model=best_model,
    topk=5
)

print(probs)
print(classes)
imshow(image)
view_classify(
    image, 
    probs, 
    classes, 
    label_map=best_model.class_to_idx, 
    version='IRIS'
)
print(model.class_to_idx['90'])

with torch.no_grad():
    if TRAIN_ON_GPU:
        model = best_model.cuda()
    else:
        model = best_model
        
    model.eval()
    accuracy = 0
    for images, labels in test_dataloader:
        if TRAIN_ON_GPU:
            images, labels = images.cuda(), labels.cuda()
            
        output = model(images)
        _, predict_class = F.softmax(output, dim=1).topk(1, dim=1)
        
        equality = predict_class == labels.view(*predict_class.shape)
        accuracy += torch.mean(equality.double())
    else:
        accuracy = accuracy/len(test_dataloader)
        
    print(accuracy)